import React, {useMemo, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { BookOpen, Gamepad2, Trophy, Languages, Download, RefreshCcw } from 'lucide-react';
import './styles.css';

const symbols = [
 ['aban','Aban','Protection','Force, sécurité et forteresse'],['abusua-pa','Abusua Pa','Famille','Unité, loyauté et solidarité familiale'],['adinkrahene','Adinkrahene','Leadership','Grandeur, charisme et autorité'],['adwo','Adwo','Calme','Paix, calme et sérénité'],['agyindawuru','Agyindawuru','Fidélité','Loyauté, vigilance et service fidèle'],['akoben','Akoben','Vigilance','Appel, vigilance et disponibilité'],['akofena','Akofena','Courage','Courage, bravoure et autorité juste'],['akoko-nan','Akoko Nan','Soin parental','Discipline, protection et soin parental'],['akoma','Akoma','Patience','Le cœur, la patience et la tolérance'],['akoma-ntoso','Akoma Ntoso','Cœurs liés','Compréhension, accord et union des cœurs'],['ananse-ntontan','Ananse Ntontan','Sagesse créative','Sagesse, créativité et complexité'],['aya','Aya','Endurance','Résilience et endurance'],['bese-saka','Bese Saka','Prospérité','Richesse, abondance et commerce'],['bi-nka-bi','Bi Nka Bi','Paix','Paix, harmonie et non-agression'],['dono','Dono','Parole sacrée','Tambour, message et communication communautaire'],['duafe','Duafe','Soin','Beauté, soin et attention'],['dwennimmen','Dwennimmen','Humilité','Force et humilité'],['eban','Eban','Protection','Sécurité, foyer et protection'],['epa','Epa','Captivité','Captivité, loi et responsabilité morale'],['fawohodie','Fawohodie','Liberté','Indépendance et liberté'],['gye-nyame','Gye Nyame','Foi','La souveraineté divine'],['hwe-mu-dua','Hwe Mu Dua','Examen','Mesure, contrôle et discernement'],['nkyinkyim','Nkyinkyim','Adaptation','Initiative, dynamisme et adaptation'],['nsaa','Nsaa','Excellence','Qualité, authenticité et excellence'],['nyansapo','Nyansapo','Sagesse','Nœud de sagesse'],['osram-ne-nsoromma','Osram ne Nsoromma','Amour','Amour, fidélité et harmonie'],['sankofa-one','Sankofa One','Mémoire','Retourner chercher le savoir oublié'],['sankofa-two','Sankofa Two','Mémoire','Autre forme du retour au savoir'],['sankofa-bird','Sankofa','Mémoire','Retourner chercher le savoir oublié'],['woforo-dua-pa','Woforo Dua Pa','Soutien','Aide, ascension et bon soutien']
].map(([id,name,short,meaning],i)=>({id,name,short,meaning,color:['#a16207','#7c3aed','#dc2626','#0f766e','#92400e','#2563eb','#15803d','#be123c'][i%8]}));

const langNames = {fr:'Français', en:'English', pt:'Português', tw:'Twi', wo:'Wolof', sw:'Kiswahili'};
function Mark({s, big=false}){ return <div className={big?'mark big':'mark'} style={{color:s.color}}><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="39" fill="none" stroke="currentColor" strokeWidth="9"/><path d="M50 15 L64 50 L50 85 L36 50 Z" fill="currentColor" opacity=".88"/><circle cx="50" cy="50" r="10" fill="#fffaf2" stroke="currentColor" strokeWidth="5"/></svg></div>}
function App(){
 const [screen,setScreen]=useState('learn'); const [lang,setLang]=useState('fr'); const [selected,setSelected]=useState(symbols[0]); const [q,setQ]=useState(0); const [score,setScore]=useState(0); const [feedback,setFeedback]=useState('');
 const question=symbols[q%symbols.length];
 const options=useMemo(()=>[question,...symbols.filter(s=>s.id!==question.id).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5),[q]);
 const answer=s=>{ if(s.id===question.id){setScore(score+10); setFeedback('Bonne réponse +10 XP'); setSelected(s)} else setFeedback('Essaie encore'); };
 return <main><header><div><b>ADINKRA WORLDS</b><span>V1 test PWA · 30 sapientogrammes prêts</span></div><select value={lang} onChange={e=>setLang(e.target.value)}>{Object.entries(langNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></header>
 <section className="hero"><div><h1>Akwaba</h1><p>Prototype installable pour test téléphone. Les 30 entrées V1 sont listées pour apprentissage et quiz.</p></div><Mark s={selected} big/></section>
 <nav><button onClick={()=>setScreen('learn')} className={screen==='learn'?'on':''}><BookOpen/>Apprendre</button><button onClick={()=>setScreen('quiz')} className={screen==='quiz'?'on':''}><Gamepad2/>Quiz</button><button onClick={()=>setScreen('audit')} className={screen==='audit'?'on':''}><Trophy/>Audit</button></nav>
 {screen==='learn'&&<section className="grid">{symbols.map(s=><button key={s.id} onClick={()=>setSelected(s)} className="card"><Mark s={s}/><b>{s.name}</b><small>{s.short}</small></button>)}</section>}
 {screen==='learn'&&<section className="detail"><Mark s={selected} big/><div><h2>{selected.name}</h2><b>{selected.short}</b><p>{selected.meaning}</p></div></section>}
 {screen==='quiz'&&<section className="quiz"><div className="score">Score : {score} XP</div><h2>Quel symbole signifie : “{question.meaning}” ?</h2><div className="grid small">{options.map(s=><button key={s.id} onClick={()=>answer(s)} className="card"><Mark s={s}/><b>{s.name}</b></button>)}</div><p className="feedback">{feedback||'—'}</p><button className="primary" onClick={()=>{setQ(q+1);setFeedback('')}}><RefreshCcw/> Question suivante</button></section>}
 {screen==='audit'&&<section className="audit"><h2>Audit V1</h2><p>Bibliothèque officielle structurée : 103 IDs. Sapientogrammes prêts : 30. Langues UI : FR / EN / PT / Twi / Wolof / Swahili.</p><p>Correction appliquée dans le canvas : le jeu “Conte” construit maintenant ses choix autour du symbole cible, afin d’éviter une question impossible.</p><p>À vérifier dans le dépôt final : remplacer ce build de test par l’export complet du canvas pour garder tous les jeux avancés.</p></section>}
 <footer><Languages/> Langue active : {langNames[lang]} · <Download/> PWA installable après déploiement HTTPS</footer></main>
}

createRoot(document.getElementById('root')).render(<App/>);
